// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.DbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929013406_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nome_categoria");

                    b.HasKey("IdCategoria")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Models.CategoriaEstabelecimento", b =>
                {
                    b.Property<int>("IdCategoriaEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_estabelecimento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoriaEstabelecimento"));

                    b.Property<string>("NomeCategoriaEstabelecimento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nome_categoria_estabelecimento");

                    b.HasKey("IdCategoriaEstabelecimento")
                        .HasName("pk_cat_estabelecimento");

                    b.ToTable("cat_estabelecimento", (string)null);
                });

            modelBuilder.Entity("Models.Estabelecimento", b =>
                {
                    b.Property<Guid>("IdEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_estabelecimento");

                    b.Property<string>("EmailEstabelecimento")
                        .HasColumnType("text")
                        .HasColumnName("email_estabelecimento");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_estabelecimento");

                    b.PrimitiveCollection<string[]>("NomeSecEstabelecimento")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("nome_sec_estabelecimento");

                    b.Property<string>("TelefoneEstabelecimento")
                        .HasColumnType("text")
                        .HasColumnName("telefone_estabelecimento");

                    b.HasKey("IdEstabelecimento")
                        .HasName("pk_estabelecimentos");

                    b.ToTable("estabelecimentos", (string)null);
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_usuario");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("senha_usuario");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
