// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.DbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001002806_CartaoMig")]
    partial class CartaoMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Cartao", b =>
                {
                    b.Property<Guid>("IdCartao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_cartao");

                    b.Property<string>("BandeiraCartao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bandeira_cartao");

                    b.Property<Guid>("DonoCartaoIdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("dono_cartao_id_usuario");

                    b.Property<decimal>("LimiteCartao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_cartao");

                    b.Property<string>("NomeCartao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_cartao");

                    b.Property<string>("NumeroCartao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("numero_cartao");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("observacoes");

                    b.Property<DateOnly>("ValidadeCartao")
                        .HasColumnType("date")
                        .HasColumnName("validade_cartao");

                    b.HasKey("IdCartao")
                        .HasName("pk_cartoes");

                    b.HasIndex("DonoCartaoIdUsuario")
                        .HasDatabaseName("ix_cartoes_dono_cartao_id_usuario");

                    b.ToTable("cartoes", (string)null);
                });

            modelBuilder.Entity("Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nome_categoria");

                    b.HasKey("IdCategoria")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Models.CategoriaEstabelecimento", b =>
                {
                    b.Property<int>("IdCategoriaEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_estabelecimento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoriaEstabelecimento"));

                    b.Property<string>("NomeCategoriaEstabelecimento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nome_categoria_estabelecimento");

                    b.HasKey("IdCategoriaEstabelecimento")
                        .HasName("pk_cat_estabelecimento");

                    b.ToTable("cat_estabelecimento", (string)null);
                });

            modelBuilder.Entity("Models.Estabelecimento", b =>
                {
                    b.Property<Guid>("IdEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_estabelecimento");

                    b.Property<int>("CategoriaEstabelecimentoIdCategoriaEstabelecimento")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_estabelecimento_id_categoria_estabelecimento");

                    b.Property<int>("CategoriaSugeridaIdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_sugerida_id_categoria");

                    b.Property<string>("EmailEstabelecimento")
                        .HasColumnType("text")
                        .HasColumnName("email_estabelecimento");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_estabelecimento");

                    b.PrimitiveCollection<string[]>("NomeSecEstabelecimento")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("nome_sec_estabelecimento");

                    b.Property<string>("TelefoneEstabelecimento")
                        .HasColumnType("text")
                        .HasColumnName("telefone_estabelecimento");

                    b.HasKey("IdEstabelecimento")
                        .HasName("pk_estabelecimentos");

                    b.HasIndex("CategoriaEstabelecimentoIdCategoriaEstabelecimento")
                        .HasDatabaseName("ix_estabelecimentos_categoria_estabelecimento_id_categoria_est");

                    b.HasIndex("CategoriaSugeridaIdCategoria")
                        .HasDatabaseName("ix_estabelecimentos_categoria_sugerida_id_categoria");

                    b.ToTable("estabelecimentos", (string)null);
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_usuario");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("senha_usuario");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Models.Cartao", b =>
                {
                    b.HasOne("Models.Usuario", "DonoCartao")
                        .WithMany()
                        .HasForeignKey("DonoCartaoIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartoes_usuarios_dono_cartao_id_usuario");

                    b.Navigation("DonoCartao");
                });

            modelBuilder.Entity("Models.Estabelecimento", b =>
                {
                    b.HasOne("Models.CategoriaEstabelecimento", "CategoriaEstabelecimento")
                        .WithMany()
                        .HasForeignKey("CategoriaEstabelecimentoIdCategoriaEstabelecimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estabelecimentos_cat_estabelecimento_categoria_estabelecime");

                    b.HasOne("Models.Categoria", "CategoriaSugerida")
                        .WithMany()
                        .HasForeignKey("CategoriaSugeridaIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estabelecimentos_categorias_categoria_sugerida_id_categoria");

                    b.Navigation("CategoriaEstabelecimento");

                    b.Navigation("CategoriaSugerida");
                });
#pragma warning restore 612, 618
        }
    }
}
